#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/inline'
require 'net/http'
require 'uri'
require 'json'
require 'yaml'
require_relative 'gen/gen'

gemfile do
  source 'https://rubygems.org'

  gem 'dotenv'
  gem 'debug'
end

execute
