#!/usr/bin/env ruby

# frozen_string_literal: true

title = ''
if ARGV.empty?
  puts 'Title: '
  title = gets.chomp
else
  title = ARGV.join(' ')
end

TIL_DIR = '/home/david/portfolio/lib/til'
file_name = title.downcase.gsub(' ', '_')
full_path = "#{TIL_DIR}/#{file_name}.md"

unless File.exist?(full_path)
  File.open(full_path, 'w') do |f|
    f.puts '---'
    f.puts "href: '/til/#{file_name}'"
    f.puts "title: #{title}"
    f.puts "excerpt: ''"
    f.puts "date: #{Time.now.strftime('%d/%m/%Y')}"
    f.puts 'tags: '
    f.puts 'published: true'
    f.puts "updated: #{Time.now.strftime('%d/%m/%Y')}"
    f.puts "topics: ''"
    f.puts '---'
    f.puts ''
    f.puts "<!-- # #{title} -->"
  end
end

system "nvim #{full_path} -c 'normal G'"
